name: Pull-Request jobs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commit-lint:
    name: ConventionalCommits Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate commit messages
        id: commit-validation
        run: |
          
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}

          types=("build" "chore" "ci" "docs" "feat" "fix" "perf" "refactor" "revert" "style" "test")
          
          commits=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/commits" \
            | jq -r '.[].commit.message')
          
          isValid=true

          while IFS= read -r commit; do
            if [[ "$commit" == *": "* ]]; then
              
              type=$(echo "$commit" | awk -F': ' '{print $1}')
              if [[ " ${types[*]} " != *" $type "* ]]; then
                echo "Type is not a valid one."
                isValid=false
              fi
              
              message=$(echo "$commit" | awk -F': ' '{print $2}')
              echo "Message: $message"
              
            else
              echo "Commit message does not contain ': ': $commit"
              isValid=false    
            fi            

          echo "isValid: $isValid"
          done <<< "$commits"
