name: Pull-Request jobs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commit-lint:
    name: Conventional Commits validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate commit messages
        id: commit-validation
        run: |
          
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}

          types=("build" "chore" "ci" "docs" "feat" "fix" "perf" "refactor" "revert" "style" "test")
          
          commits=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/commits" \
            | jq -r '.[].commit.message')

          echo "$commits"
          
          isValid=true

          # Process each commit message
          while IFS= read -r commit; do
            # Extract type and message
            type=$(echo "$commit" | cut -d': ' -f1)
            message=$(echo "$commit" | cut -d': ' -f2-)

            # Validate the type
            if [[ ! " ${types[@]} " =~ " ${type} " ]]; then
              echo "Commit type is invalid for commit: $commit"
              isValid=false
            fi

            # Validate the message
            if [[ ! $message =~ ^[a-z ]{1,50}$ ]]; then
              echo "Commit message is not in lowercase or length is greater than 50 for commit: $commit"
              isValid=false
            fi
            
          done <<< "$commits"

          # Exit with non-zero status if validation failed
          if [ "$isValid" = false ]; then
            echo "Commit validation failed"
            exit 1
          fi

      - name: Comment on PR if commit messages are invalid
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Conventional Commits**\n\nAll commits should follow Conventional Commits convention.\n\nPlease refer to: https://www.conventionalcommits.org/en/v1.0.0/`
            });
